// =============================================================
// exp_piecewise.h  –  32-segment piecewise-linear exp(x)
//   for x in [-8, 0].  Fully combinational, 1-cycle latency.
//   AUTO-GENERATED by gen_piecewise_exp.py  –  do not hand-edit
// =============================================================
#pragma once
#include <ap_fixed.h>

// Number of segments
#define PW_EXP_NSEG 32

// Include exp_ip.h to get the types exp_in_t and exp_out_t
#include "exp_ip.h"

// Output type: exp(x) for x<=0 is in (0, 1].
// ap_fixed<18, 1> gives 1 sign + 0 extra int + 17 frac bits.
typedef ap_fixed<18, 1> pw_exp_t;

// Internal coefficient type – wide enough for slopes up to ~4
typedef ap_fixed<20, 3> pw_coeff_t;

// ---- LUT base values  exp(x_lo) for each segment ----
static const pw_coeff_t PW_BASE[PW_EXP_NSEG] = {
    (pw_coeff_t)0.000335462627903, // seg 0: x=-8.00
    (pw_coeff_t)0.000430742540576, // seg 1: x=-7.75
    (pw_coeff_t)0.000553084370148, // seg 2: x=-7.50
    (pw_coeff_t)0.000710174388843, // seg 3: x=-7.25
    (pw_coeff_t)0.000911881965555, // seg 4: x=-7.00
    (pw_coeff_t)0.001170879620791, // seg 5: x=-6.75
    (pw_coeff_t)0.001503439192978, // seg 6: x=-6.50
    (pw_coeff_t)0.001930454136228, // seg 7: x=-6.25
    (pw_coeff_t)0.002478752176666, // seg 8: x=-6.00
    (pw_coeff_t)0.003182780796510, // seg 9: x=-5.75
    (pw_coeff_t)0.004086771438464, // seg 10: x=-5.50
    (pw_coeff_t)0.005247518399181, // seg 11: x=-5.25
    (pw_coeff_t)0.006737946999085, // seg 12: x=-5.00
    (pw_coeff_t)0.008651695203121, // seg 13: x=-4.75
    (pw_coeff_t)0.011108996538242, // seg 14: x=-4.50
    (pw_coeff_t)0.014264233908999, // seg 15: x=-4.25
    (pw_coeff_t)0.018315638888734, // seg 16: x=-4.00
    (pw_coeff_t)0.023517745856009, // seg 17: x=-3.75
    (pw_coeff_t)0.030197383422319, // seg 18: x=-3.50
    (pw_coeff_t)0.038774207831722, // seg 19: x=-3.25
    (pw_coeff_t)0.049787068367864, // seg 20: x=-3.00
    (pw_coeff_t)0.063927861206708, // seg 21: x=-2.75
    (pw_coeff_t)0.082084998623899, // seg 22: x=-2.50
    (pw_coeff_t)0.105399224561864, // seg 23: x=-2.25
    (pw_coeff_t)0.135335283236613, // seg 24: x=-2.00
    (pw_coeff_t)0.173773943450445, // seg 25: x=-1.75
    (pw_coeff_t)0.223130160148430, // seg 26: x=-1.50
    (pw_coeff_t)0.286504796860190, // seg 27: x=-1.25
    (pw_coeff_t)0.367879441171442, // seg 28: x=-1.00
    (pw_coeff_t)0.472366552741015, // seg 29: x=-0.75
    (pw_coeff_t)0.606530659712633, // seg 30: x=-0.50
    (pw_coeff_t)0.778800783071405  // seg 31: x=-0.25
};

// ---- LUT slope values  (exp(x_hi) - exp(x_lo)) / seg_width ----
static const pw_coeff_t PW_SLOPE[PW_EXP_NSEG] = {
    (pw_coeff_t)0.000381119650693, // seg 0
    (pw_coeff_t)0.000489367318289, // seg 1
    (pw_coeff_t)0.000628360074779, // seg 2
    (pw_coeff_t)0.000806830306848, // seg 3
    (pw_coeff_t)0.001035990620947, // seg 4
    (pw_coeff_t)0.001330238288746, // seg 5
    (pw_coeff_t)0.001708059773001, // seg 6
    (pw_coeff_t)0.002193192161755, // seg 7
    (pw_coeff_t)0.002816114479373, // seg 8
    (pw_coeff_t)0.003615962567818, // seg 9
    (pw_coeff_t)0.004642987842869, // seg 10
    (pw_coeff_t)0.005961714399616, // seg 11
    (pw_coeff_t)0.007654992816141, // seg 12
    (pw_coeff_t)0.009829205340487, // seg 13
    (pw_coeff_t)0.012620949483028, // seg 14
    (pw_coeff_t)0.016205619918940, // seg 15
    (pw_coeff_t)0.020808427869100, // seg 16
    (pw_coeff_t)0.026718550265238, // seg 17
    (pw_coeff_t)0.034307297637614, // seg 18
    (pw_coeff_t)0.044051442144568, // seg 19
    (pw_coeff_t)0.056563171355375, // seg 20
    (pw_coeff_t)0.072628549668765, // seg 21
    (pw_coeff_t)0.093256903751862, // seg 22
    (pw_coeff_t)0.119744234698993, // seg 23
    (pw_coeff_t)0.153754640855330, // seg 24
    (pw_coeff_t)0.197424866791939, // seg 25
    (pw_coeff_t)0.253498546847041, // seg 26
    (pw_coeff_t)0.325498577245009, // seg 27
    (pw_coeff_t)0.417948446278289, // seg 28
    (pw_coeff_t)0.536656427886475, // seg 29
    (pw_coeff_t)0.689080493435086, // seg 30
    (pw_coeff_t)0.884796867714380  // seg 31
};

// ---- Piecewise-linear exp(x) for x in [-8, 0] ----
// Fully inlined → replicates per call-site (no BRAM, no sharing limit).
static inline pw_exp_t exp_piecewise(ap_fixed<16, 4> x) {
#pragma HLS INLINE
#pragma HLS PIPELINE II = 1
  if (x < (ap_fixed<16, 4>)(-8.0))
    return (exp_out_t)0;
  if (x >= (ap_fixed<16, 4>)(0.0))
    return (exp_out_t)1;

  // offset in [0, 8)
  ap_ufixed<16, 4> offset = (ap_ufixed<16, 4>)(x + (ap_fixed<16, 4>)8.0);

  // segment index = floor(offset / 0.25) = floor(offset * 4)
  // offset has 12 frac bits; bit 10 is 2^-2. Thus bits [15:10] represent the
  // integer * 4. We use 6 bits to prevent truncation when offset
  // approaches 8.0.
  ap_uint<6> seg = offset.range(15, 10);
  if (seg > 31)
    seg = 31;

  // fractional position within the segment, correctly sized
  // offset.range(9, 0) represents the remainder, which fits in [0, 0.25)
  // We place it directly into the fractional part.
  ap_ufixed<12, 0> frac_raw;
  frac_raw.range(9, 0) = offset.range(9, 0);
  frac_raw.range(11, 10) = 0;

  // result = base[seg] + frac * slope[seg]
  pw_coeff_t base_val = PW_BASE[seg];
  pw_coeff_t slope_val = PW_SLOPE[seg];
  pw_coeff_t result = base_val + (pw_coeff_t)(frac_raw * slope_val);

  // Clamp to [0, 1]
  if (result < 0)
    result = 0;
  if (result > (pw_coeff_t)1.0)
    result = (pw_coeff_t)1.0;

  return (exp_out_t)result;
}
