# gen_fixed_model.py
#
# Reads the GIVEN headers:
#   c_headers/svs.h     (double svs[] = {...};)
#   c_headers/alphas.h  (double alphas[] = {...};)
#   c_headers/bias.h    (double bias[] = {...};)
#
# Quantizes to the coursework formats:
#   svs_q   : ap_fixed<8,7>  (7 int incl sign, 1 frac)
#   alphas_q: ap_fixed<8,5>  (5 int incl sign, 3 frac)
#   bias_q  : ap_fixed<8,1>  (1 int incl sign, 7 frac)
#
# Emits: svm_model_fixed_data.h with macros:
#   SVS_Q_INIT, ALPHAS_Q_INIT, BIAS_Q_INIT
#
# Run:
#   python3 gen_fixed_model.py

import re
from pathlib import Path

DIM = 784
NSV = 165


def parse_c_array(text: str, name: str):
    """
    Parse C header array like:
      double name[] = { ... };
    Returns list[float].
    """
    pat = rf"\bdouble\s+{re.escape(name)}\s*\[\s*\]\s*=\s*\{{(.*?)\}}\s*;"
    m = re.search(pat, text, re.S)
    if not m:
        raise RuntimeError(f"Could not find array '{name}' in header.")
    body = m.group(1)

    # Extract numeric literals (handles floats, ints, exponent notation)
    nums = re.findall(
        r"[-+]?\d*\.\d+(?:[eE][-+]?\d+)?|[-+]?\d+(?:[eE][-+]?\d+)?",
        body
    )
    if not nums:
        raise RuntimeError(f"Array '{name}' appears empty or unparsable.")
    return [float(x) for x in nums]


def q_signed(x: float, int_bits: int, frac_bits: int) -> float:
    """
    Quantize to signed fixed-point with:
      total bits = int_bits + frac_bits
      int_bits includes sign
    Saturate to representable range and round to nearest step.
    """
    step = 2.0 ** (-frac_bits)
    lo = -(2.0 ** (int_bits - 1))
    hi = (2.0 ** (int_bits - 1)) - step

    if x < lo:
        x = lo
    elif x > hi:
        x = hi

    return round(x / step) * step


def fmt_feat(v: float) -> str:
    # ap_fixed<8,7> => frac=1
    return f"(feat_t){q_signed(v, 7, 1):.10g}"


def fmt_alpha(v: float) -> str:
    # ap_fixed<8,5> => frac=3
    return f"(alpha_t){q_signed(v, 5, 3):.10g}"


def fmt_bias(v: float) -> str:
    # ap_fixed<8,1> => frac=7
    return f"(bias_t){q_signed(v, 1, 7):.10g}"


def main():
    svs_h = Path("c_headers/svs.h").read_text()
    alphas_h = Path("c_headers/alphas.h").read_text()
    bias_h = Path("c_headers/bias.h").read_text()

    svs = parse_c_array(svs_h, "svs")
    alphas = parse_c_array(alphas_h, "alphas")
    bias = parse_c_array(bias_h, "bias")

    # Sanity checks
    if len(svs) != NSV * DIM:
        raise RuntimeError(f"svs length {len(svs)} != {NSV*DIM}")
    if len(alphas) != NSV:
        raise RuntimeError(f"alphas length {len(alphas)} != {NSV}")
    if len(bias) != 1:
        raise RuntimeError(f"bias length {len(bias)} != 1")

    out = []
    out.append("#pragma once")
    out.append("// AUTO-GENERATED by gen_fixed_model.py. Do not edit by hand.")
    out.append('#include "svm_classifier.h"')
    out.append("")

        # SVS_Q_INIT macro (2D initializer)
    out.append("#define SVS_Q_INIT { \\")
    for i in range(NSV):
        row = svs[i * DIM:(i + 1) * DIM]
        elems = ", ".join(fmt_feat(v) for v in row)

        # IMPORTANT: always end rows with '\' so the macro continues to the final closing brace line.
        line = "  { " + elems + " }, \\"
        out.append(line)

    # Final closing brace line of the macro (NO backslash here)
    out.append("}")
    out.append("")

    # ALPHAS_Q_INIT macro
    out.append("#define ALPHAS_Q_INIT { " + ", ".join(fmt_alpha(v) for v in alphas) + " }")
    out.append("")

    # BIAS_Q_INIT macro
    out.append("#define BIAS_Q_INIT { " + fmt_bias(bias[0]) + " }")
    out.append("")

    Path("svm_model_fixed_data.h").write_text("\n".join(out))
    print("Wrote svm_model_fixed_data.h")


if __name__ == "__main__":
    main()